/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:29:37 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsKit.framework/UserNotificationsKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSCopying
@required
-(id)copyWithZone:(NSZone*)arg1;

@end

