/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:32 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/VoiceTrigger.framework/VoiceTrigger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VoiceTrigger/VTPolicy.h>

@interface VTAssetManagerEnablePolicy : VTPolicy
-(id)init;
-(void)_subscribeEventMonitors;
-(void)_addAssetManagerEnabledConditions;
@end

