//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL, _SFNavigationBar, _UIBackdropViewSettings;

@protocol _SFNavigationBarDelegate <NSObject>
- (void)navigationBarReaderAppearanceButtonWasTapped:(_SFNavigationBar *)arg1;
- (NSURL *)navigationBarURLForSharing:(_SFNavigationBar *)arg1;
- (void)navigationBarStopLoadingButtonWasTapped:(_SFNavigationBar *)arg1;
- (void)navigationBarReloadButtonWasLongPressed:(_SFNavigationBar *)arg1;
- (void)navigationBarReloadButtonWasTapped:(_SFNavigationBar *)arg1;
- (void)navigationBarCancelButtonWasTapped:(_SFNavigationBar *)arg1;
- (void)navigationBarReaderButtonWasTapped:(_SFNavigationBar *)arg1;
- (void)navigationBarBackdropDidApplySettings:(_SFNavigationBar *)arg1;
- (void)navigationBarURLWasTapped:(_SFNavigationBar *)arg1;
- (void)compressedNavigationBarWasTapped:(_SFNavigationBar *)arg1;

@optional
- (void)navigationBar:(_SFNavigationBar *)arg1 backDropWillApplySettings:(_UIBackdropViewSettings *)arg2;
- (void)navigationBar:(_SFNavigationBar *)arg1 didPasteText:(NSString *)arg2;
- (void)navigationBarDoneButtonWasTapped:(_SFNavigationBar *)arg1;
@end

