//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ActionPanelPrintRendererActivityItemProvider.h"

@class UIPrintInfo, WBUPrintPageRenderer;

@interface ActionPanelPrintInfoActivityItemProvider : ActionPanelPrintRendererActivityItemProvider
{
    UIPrintInfo *_printInfo;
    WBUPrintPageRenderer *_printRenderer;
}

- (void).cxx_destruct;
- (id)item;
- (id)initWithPlaceholderItem:(id)arg1 tabDocument:(id)arg2;
- (id)initWithTabDocument:(id)arg1 printRenderer:(id)arg2;

@end

