//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFManagedActivityViewController.h>

@class TabDocument;
@protocol ActionPanelDelegate;

@interface ActionPanel : _SFManagedActivityViewController
{
    _Bool _inCancel;
    _Bool _inCompletionHandler;
    TabDocument *_tabDocument;
}

@property(readonly, nonatomic) TabDocument *tabDocument; // @synthesize tabDocument=_tabDocument;
- (void).cxx_destruct;
- (id)excludedActivityTypes;
- (void)_preparePrint:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_prepareMail:(id)arg1;
- (void)_preparePostToSocialNetwork:(id)arg1;
- (id)_titleForActivity:(id)arg1;
- (void)_prepareActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_executeActivity;
- (void)_cancel;
- (void)_activityDidComplete:(id)arg1 withSuccess:(_Bool)arg2;
- (void)activityDidComplete:(id)arg1 withReturnedItems:(id)arg2 success:(_Bool)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (id)initWithTabDocument:(id)arg1 activityDelegate:(id)arg2;

// Remaining properties
@property(nonatomic) __weak id <ActionPanelDelegate> delegate; // @dynamic delegate;

@end

