//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_SFActivityViewControllerDelegate-Protocol.h"

@class ActionPanel, MFMailComposeViewController;

@protocol ActionPanelDelegate <_SFActivityViewControllerDelegate>
- (void)actionPanel:(ActionPanel *)arg1 prepareForMailActivityWithMailController:(MFMailComposeViewController *)arg2;
- (_Bool)actionPanelAddTabDocumentToReadingList:(ActionPanel *)arg1;
@end

