//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

#import "BrowserWindowControllerDelegate-Protocol.h"
#import "BrowserWindowControllerObserving-Protocol.h"
#import "MCProfileConnectionObserver-Protocol.h"
#import "MobileSafariWindowDelegate-Protocol.h"
#import "PageLoadTestRunnerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "WBDatabaseLockAcquisitorDelegate-Protocol.h"

@class ApplicationShortcutController, BookmarksDatabaseHealthReporter, BrowserContainerViewController, BrowserWindowController, DragOverlayViewController, MobileSafariWindow, NSArray, NSDictionary, NSString, SBSAssertion, TabDocument, UIViewController, UIWindow, WBDatabaseLockAcquisitor, WBSCloudHistory, WBSFormAutoFillCorrectionsHistoryObserver;
@protocol DragInteractionDriver;

@interface Application : UIApplication <PageLoadTestRunnerDelegate, BrowserWindowControllerDelegate, BrowserWindowControllerObserving, MCProfileConnectionObserver, MobileSafariWindowDelegate, WBDatabaseLockAcquisitorDelegate, UIApplicationDelegate>
{
    _Bool _isReadingDefaults;
    _Bool _shouldReadDefaultsOnResume;
    _Bool _isRunningShowBookmarksTest;
    _Bool _startedBookmarksTest;
    _Bool _isRunningCanvasTest;
    _Bool _willEnterSuspendedState;
    _Bool _shouldPrepareTabDocumentForNewUserActivityWhenFinishedLaunching;
    _Bool _finishedLaunching;
    WBSCloudHistory *_cloudHistory;
    _Bool _resigningActive;
    _Bool _shouldAnimateOpeningExternalURL;
    long long _currentKeyboardModifierFlags;
    ApplicationShortcutController *_shortcutController;
    UIViewController *_obfuscatedScreenViewController;
    NSDictionary *_openURLPayload;
    MobileSafariWindow *_window;
    BrowserContainerViewController *_containerViewController;
    DragOverlayViewController *_dragOverlayViewController;
    UIWindow *_dragWindow;
    id <DragInteractionDriver> _dragInteractionDriver;
    WBSFormAutoFillCorrectionsHistoryObserver *_formAutoFillCorrectionsHistoryObserver;
    BookmarksDatabaseHealthReporter *_bookmarksDatabaseHealthReporter;
    unsigned long long _bookmarksDatabaseBackgroundTaskIdentifier;
    WBDatabaseLockAcquisitor *_bookmarksDatabaseBackgroundTaskLockAcquisitor;
    SBSAssertion *_wallpaperSuspensionAssertion;
    BrowserWindowController *_browserWindowController;
    TabDocument *_tabDocumentPendingUserActivityPayload;
}

+ (unsigned long long)systemMemorySize;
+ (void)initialize;
+ (id)sharedApplication;
+ (id)sharedTestRunner;
+ (void)commandLineTestOption:(int)arg1 arg:(const char *)arg2;
+ (void)postTestNotificationName:(id)arg1 object:(id)arg2;
@property(nonatomic) __weak TabDocument *tabDocumentPendingUserActivityPayload; // @synthesize tabDocumentPendingUserActivityPayload=_tabDocumentPendingUserActivityPayload;
@property(retain, nonatomic) WBSCloudHistory *cloudHistory; // @synthesize cloudHistory=_cloudHistory;
@property(readonly, nonatomic) BrowserWindowController *browserWindowController; // @synthesize browserWindowController=_browserWindowController;
- (void).cxx_destruct;
- (void)_reloadContainerViewController;
- (void)windowController:(id)arg1 didRemoveWindow:(id)arg2;
- (void)windowController:(id)arg1 didAddWindow:(id)arg2 withSourceInfo:(id)arg3;
- (long long)resolveUnspecifiedPositionForBrowserWindowController:(id)arg1;
- (void)safariWindow:(id)arg1 didEndAllTouchesAtPoint:(struct CGPoint)arg2;
- (void)safariWindow:(id)arg1 statusBarChangedFromHeight:(double)arg2 toHeight:(double)arg3;
- (void)_getBookmarksDataClassEnabledWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_updateCloudFeatureAvailability;
- (void)_prepareTabDocumentForNewUserActivity;
@property(retain, nonatomic) UIWindow *window;
- (void)applicationWillTerminate;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)endDragInteractionWithPoint:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateDragInteractionWithPoint:(struct CGPoint)arg1;
- (void)beginDragInteractionWithDragContext:(id)arg1;
- (_Bool)canBeginNewDragInteraction;
- (void)updateTabCount;
- (void)auditTabCount;
- (_Bool)canAddNewTabForPrivateBrowsing:(_Bool)arg1;
- (unsigned long long)_maximumTabCount;
- (unsigned long long)_numberOfTabsForPrivateBrowsing:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_removeDefaultsObserver;
- (void)_addDefaultsObserver;
- (void)_managedProfileConfigurationDidUpdate;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)_setHandlingURL:(_Bool)arg1 url:(id)arg2;
- (void)_appleKeyboardsChanged:(id)arg1;
- (void)_reloadSearchEngines;
- (void)userDefaultsDidChange:(id)arg1;
- (id)_openURLInNewTab:(id)arg1 withOptions:(id)arg2;
@property(readonly, nonatomic) ApplicationShortcutController *shortcutController;
- (void)handleKeyUIEvent:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)_applicationOpenURL:(id)arg1 payload:(id)arg2;
- (void)applicationOpenURL:(id)arg1;
- (void)_saveBrowserState;
- (void)didReceiveMemoryWarning;
- (void)_saveNSURLCacheToDiskInBackground:(_Bool)arg1;
- (void)databaseLockAcquisitor:(id)arg1 acquiredLock:(_Bool)arg2;
- (void)_performBookmarksDatabaseTasksInBackground;
- (void)_suspendOrResumeWallpaperAnimationIfNeeded;
- (void)_dismissObfuscatedScreenViewController;
- (void)_presentObfuscatedScreenViewController;
- (void)_reportBookmarksDatabaseHealth;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)clearReaderViewsExceptMultiplePageReader:(_Bool)arg1;
- (_Bool)shouldReportForegroundTabCrash;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)saveChangesToCloudHistoryStore;
- (void)_application:(id)arg1 statusBarTouchesEnded:(id)arg2;
- (void)_applicationWillSuspend:(id)arg1;
- (void)_readDefaults;
@property(readonly, nonatomic, getter=isPrivateBrowsingEnabledInAnyWindow) _Bool privateBrowsingEnabledInAnyWindow;
- (id)_focusedBrowserController;
- (id)_browserControllerForExternalNavigation;
@property(readonly, nonatomic) NSArray *browserControllers;
- (_Bool)didStartBookmarksTest;
- (_Bool)isRunningCanvasTest;
- (_Bool)isRunningShowBookmarksTest;
- (void)runSplitViewTest;
- (void)runBookmarksViewTest;
- (id)_switchToScrollViewForTestNamed:(id)arg1;
- (void)setTestAnimationCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CDUnknownBlockType testAnimationCompletionHandler;
- (void)_populateInMemoryBookmarksDBForTestNamed:(id)arg1;
- (void)finishedBookmarksTest;
- (void)startBookmarksTest;
- (_Bool)prepareBookmarksTest;
- (void)_runTabOverviewScrollPerfTest;
- (void)_runTabOverviewPresentingAndDismissalTest;
- (void)runTabOverviewTest;
- (void)finishedCanvasTestWithURL:(id)arg1 forTabDocument:(id)arg2;
- (void)_pollCanvasTest:(id)arg1;
- (_Bool)startCanvasTest:(id)arg1;
- (void)failedPurpleTestWithError:(id)arg1;
- (void)finishedPurpleTest:(id)arg1;
- (void)startedPurpleTest;
- (void)startTabViewRotationTest;
- (void)_prepareTabViewRotationTest;
- (void)prepareTabViewRotationTest;
- (void)startTabViewCloseTest;
- (void)_prepareTabViewCloseTest;
- (void)prepareTabViewCloseTest;
- (void)startTabViewSelectTest;
- (void)_prepareTabViewSelectTest;
- (void)prepareTabViewSelectTest;
- (void)startTabViewOpenTest;
- (void)_prepareTabViewOpenTest;
- (void)prepareTabViewOpenTest;
- (void)startTabViewBringUpTest;
- (void)_prepareTabViewBringUpTest;
- (void)prepareTabViewBringUpTest;
- (void)loadTabsForTesting:(unsigned long long)arg1 presentTabView:(_Bool)arg2;
- (void)loadBlankPageforKeyboardTests;
- (void)startKeyboardRotationTest;
- (void)startKeyboardBringupTest;
- (void)startKeyboardSplitAndMergeTest;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (id)_numberOption:(id)arg1;
- (void)checkExtendedLaunchPageLoad:(id)arg1 forTabDocument:(id)arg2;
- (id)_extendLaunchTest;
- (_Bool)overrideBrowserStateForTestNamed:(id)arg1 existingUUID:(id)arg2;
- (_Bool)disableRestoreTabState;
- (void)startCommandLineTest;
- (id)_browserControllerForApplicationTesting;
- (void)pageLoadTestRunnerFinished:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

