//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BrowserController, UIApplicationShortcutItem;

@interface ApplicationShortcutController : NSObject
{
    UIApplicationShortcutItem *_showReadingListShortcutItem;
    UIApplicationShortcutItem *_showBookmarksShortcutItem;
    UIApplicationShortcutItem *_newPrivateTabShortcutItem;
    UIApplicationShortcutItem *_newTabShortcutItem;
    BrowserController *_browserController;
}

@property(nonatomic) __weak BrowserController *browserController; // @synthesize browserController=_browserController;
- (void).cxx_destruct;
- (void)updateShortcutItemsIfNeeded;
- (id)_shortcutItems;
- (void)_showBookmarksPanelWithSelectedCollection:(id)arg1;
- (void)_openNewEmptyTabWithURLFieldFocused:(_Bool)arg1 privateBrowsingState:(long long)arg2;
- (id)_shortcutItemWithType:(id)arg1 iconTemplate:(id)arg2;
- (_Bool)handleShortcutItemWithType:(id)arg1;
- (id)init;

@end

