//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class WebBookmark;

@interface BookmarksBarLabelButton : UIButton
{
    _Bool _usesLightControls;
    WebBookmark *_bookmark;
}

+ (id)labelButton;
@property(nonatomic) _Bool usesLightControls; // @synthesize usesLightControls=_usesLightControls;
@property(retain, nonatomic) WebBookmark *bookmark; // @synthesize bookmark=_bookmark;
- (void).cxx_destruct;
- (void)layoutSubviews;

@end

