//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BookmarkFavoritesGridViewDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate_Private-Protocol.h"

@class BookmarkFavoritesGridView, NSString, WebBookmarkCollection, WebBookmarkList;
@protocol BookmarkFavoritesViewControllerDelegate;

@interface BookmarkFavoritesViewController : UIViewController <BookmarkFavoritesGridViewDelegate, UIViewControllerPreviewingDelegate, UIViewControllerPreviewingDelegate_Private>
{
    WebBookmarkCollection *_collection;
    WebBookmarkList *_favoritesList;
    _Bool _showWhitelistFavorites;
    BookmarkFavoritesGridView *_favoritesGridView;
    id <BookmarkFavoritesViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <BookmarkFavoritesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (long long)bookmarkFavoritesGridViewLayoutType:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 updatedContentSize:(struct CGSize)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 banFrequentlyVisitedSite:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 promoteFrequentlyVisitedSite:(id)arg2 toFavoriteAtIndex:(unsigned long long)arg3;
- (void)bookmarkFavoritesGridViewDidReorderBookmarks:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 deleteBookmark:(id)arg2;
- (void)bookmarkFavoritesGridView:(id)arg1 editBookmark:(id)arg2;
- (_Bool)bookmarkFavoritesGridViewCanPromoteFrequentlyVisitedSiteToFavorite:(id)arg1;
- (_Bool)bookmarkFavoritesGridView:(id)arg1 canCommitReorderingBookmarkFromIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)bookmarkFavoritesGridView:(id)arg1 didReorderBookmarkFromIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (_Bool)bookmarkFavoritesGridViewShouldReorderBookmarks:(id)arg1;
- (void)didTapOutsideBookmarkFavoritesGridView:(id)arg1;
- (void)bookmarkFavoritesGridView:(id)arg1 didSelectBookmark:(id)arg2;
- (void)setScrollViewScrollsToTop:(_Bool)arg1;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)loadFavoritesList;
- (void)_updateFavoritesListDueToBookmarksReload:(_Bool)arg1;
- (void)_recomputeFrequentlyVisitedSitesIfNecessary;
- (void)_updateVisibleFrequentlyVisitedSites;
- (void)_receivedFrequentlyVisitedSitesDidChangeNotification:(id)arg1;
- (void)_receivedBookmarksFolderContentChangedNotification:(id)arg1;
- (void)_receivedBookmarksReloadOrSpecialFolderChangeNotification:(id)arg1;
- (_Bool)_canReorderFavorites;
- (id)bookmarksNavigationController;
- (void)setAdjustedForSidebar:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)test_overrideBookmarkCollection:(id)arg1;
- (void)dealloc;
- (id)initWithBookmarksCollection:(id)arg1 showWhiteListFavorites:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

