//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertController.h>

#import "_SFSingleBookmarkNavigationControllerDelegate-Protocol.h"

@class SingleBookmarkNavigationController, TabDocument;

@interface BookmarkLongPressAlertController : UIAlertController <_SFSingleBookmarkNavigationControllerDelegate>
{
    SingleBookmarkNavigationController *_bookmarkNavController;
    TabDocument *_tabDocument;
}

+ (void)_addActionForCancelButtonToAlertController:(id)arg1;
+ (void)_addActionForAddToReadingListButtonToAlertController:(id)arg1;
+ (void)_addActionForAddToSharedLinksButtonToAlertController:(id)arg1;
+ (void)_addActionForAddBookmarkButtonToAlertController:(id)arg1;
+ (_Bool)isAlertControllerAvailableForTabDocument:(id)arg1;
+ (id)alertControllerWithTabDocument:(id)arg1;
- (void).cxx_destruct;
- (_Bool)addBookmarkNavControllerCanSaveBookmarkChanges:(id)arg1;
- (void)addBookmarkNavController:(id)arg1 didFinishWithResult:(_Bool)arg2;
- (void)_subscribeInSharedLinks;
- (void)_addToReadingList;
- (void)_addBookmark;

@end

