//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFPopoverSizingTableViewController.h>

#import "BookmarksPanelStateRestoring-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "_SFBookmarkInfoViewControllerDelegate-Protocol.h"

@class NSString, UISearchBar, WebBookmark, WebBookmarkCollection, WebBookmarkList;
@protocol BookmarksTableViewControllerDelegate, LinkPreviewProvider;

@interface BookmarksTableViewController : _SFPopoverSizingTableViewController <UISearchBarDelegate, _SFBookmarkInfoViewControllerDelegate, BookmarksPanelStateRestoring>
{
    WebBookmarkCollection *_collection;
    WebBookmarkList *_bookmarkList;
    WebBookmark *_favoritesFolder;
    UISearchBar *_searchBar;
    NSString *_userTypedFilter;
    unsigned long long _skipOffset;
    _Bool _needsInitialContentOffsetUpdateForTableHeaderView;
    _Bool _needsContentOffsetUpdate;
    double _restoredScrollPosition;
    WebBookmark *_folder;
    id <BookmarksTableViewControllerDelegate> _delegate;
    id <LinkPreviewProvider> _linkPreviewProvider;
}

@property(nonatomic) __weak id <LinkPreviewProvider> linkPreviewProvider; // @synthesize linkPreviewProvider=_linkPreviewProvider;
@property(nonatomic) __weak id <BookmarksTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WebBookmark *folder; // @synthesize folder=_folder;
- (void).cxx_destruct;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)commitPreviewViewController:(id)arg1;
- (id)previewViewControllerForRowAtIndexPath:(id)arg1;
- (_Bool)bookmarkInfoViewControllerShouldUseTranslucentAppearance:(id)arg1;
- (_Bool)hasTranslucentAppearance;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (id)selectedBookmarks;
@property(readonly, nonatomic) NSString *collectionType;
- (void)restoreScrollPosition:(double)arg1;
- (double)currentScrollPosition;
- (_Bool)restoreStateWithDictionary:(id)arg1;
- (id)currentStateDictionary;
- (void)setScrollViewScrollsToTop:(_Bool)arg1;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateTableViewCellsTextStyleForEditing:(_Bool)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_pushInfoViewControllerForBookmark:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)_tableViewCellForBookmark:(id)arg1;
- (id)_grayedOutHistoryFolderIcon;
- (id)_grayedOutFavoriteFolderIcon;
- (id)_tintedImageNamed:(id)arg1;
- (id)bookmarksTableViewCellWithReuseIdentifier:(id)arg1;
- (id)_bookmarkAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)_collectionForRowAtIndexPath:(id)arg1;
- (void)_updateContentOffsetIfNeeded;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)updateSeparatorInset;
- (void)traitCollectionDidChange:(id)arg1;
- (void)loadView;
- (id)bookmarksNavigationController;
@property(readonly, nonatomic) int folderID;
- (void)reloadBookmarks;
- (void)_recreateBookmarkLists;
- (_Bool)_inRootFolder;
- (void)_updateTitle;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 inCollection:(id)arg2 skipOffset:(unsigned int)arg3;
- (id)initWithFolder:(id)arg1 inCollection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

