//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface BrowserContainerSeparatorView : UIView
{
    UIView *_bottomBarSeparatorView;
    UIView *_contentSeparatorView;
    long long _style;
    UIView *_topBarSeparatorView;
    struct UIEdgeInsets _barInsets;
}

@property(nonatomic) struct UIEdgeInsets barInsets; // @synthesize barInsets=_barInsets;
- (void).cxx_destruct;
- (void)transitionToStyle:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

