//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class BrowserController, CatalogViewController;

@interface BrowserRootViewController : UIViewController
{
    long long _preferredStatusBarStyle;
    long long _preferredWhitePointAdaptivityStyle;
    _Bool _canBecomeFirstResponder;
    BrowserController *_browserController;
    CatalogViewController *_catalogViewController;
}

@property(retain, nonatomic) CatalogViewController *catalogViewController; // @synthesize catalogViewController=_catalogViewController;
@property(readonly, nonatomic) __weak BrowserController *browserController; // @synthesize browserController=_browserController;
- (void).cxx_destruct;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)overrideTraitCollectionForChildViewController:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (long long)sizeClassForWidth:(double)arg1;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)loadView;
- (_Bool)safari_wantsTransparentApplicationBackground;
- (struct UIEdgeInsets)_avoidanceInsets;
@property(nonatomic) long long preferredWhitePointAdaptivityStyle;
@property(nonatomic) long long preferredStatusBarStyle;
- (id)initWithBrowserController:(id)arg1;

@end

