//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class BrowserContainerArrangement, BrowserContainerSeparatorView, NSArray, NSValue, UITraitCollection, UIView;
@protocol BrowserContainerViewControllerDelegate;

@interface BrowserContainerViewController : UIViewController
{
    struct CGRect _arrangementOverrideFrame;
    unsigned long long _arrangementOverrideIndex;
    BrowserContainerArrangement *_currentArrangement;
    CDUnknownBlockType _deferredLayoutTransitionCompletion;
    NSArray *_displayedBrowserControllers;
    UIView *_hintingTransformContainerView;
    struct _NSRange _preferredOnScreenChildRange;
    _Bool _sentDidChangeArrangement;
    BrowserContainerSeparatorView *_separatorView;
    NSValue *_targetSizeForTransition;
    UITraitCollection *_targetTraitCollectionForTransition;
    _Bool _usesDeferredLayoutTransitionCompletion;
    id <BrowserContainerViewControllerDelegate> _delegate;
    unsigned long long _preferredOnScreenCapacity;
    NSArray *_browserControllers;
    long long _newWindowHintingEdge;
}

@property(nonatomic) long long newWindowHintingEdge; // @synthesize newWindowHintingEdge=_newWindowHintingEdge;
@property(copy, nonatomic) NSArray *browserControllers; // @synthesize browserControllers=_browserControllers;
@property(readonly, nonatomic) unsigned long long preferredOnScreenCapacity; // @synthesize preferredOnScreenCapacity=_preferredOnScreenCapacity;
@property(nonatomic) __weak id <BrowserContainerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)onScreenBrowserControllerAfter:(id)arg1;
- (id)browserControllerAtPoint:(struct CGPoint)arg1;
@property(readonly, nonatomic) _Bool isDisplayingMultipleControllers;
@property(readonly, nonatomic) _Bool canDisplayMultipleControllers;
@property(readonly, nonatomic) struct CGSize childSizeForNextBrowserController;
- (struct _NSRange)_rangeOfSubarrayInDisplayedBrowserControllers:(id)arg1;
- (void)_removeChildBrowserController:(id)arg1;
- (void)_addChildBrowserController:(id)arg1;
- (void)setBrowserControllers:(id)arg1 withInitialFrame:(struct CGRect)arg2 forBrowserController:(id)arg3;
- (_Bool)safari_wantsTransparentApplicationBackground;
- (void)invalidateArrangement;
- (id)currentArrangement;
- (void)_createArrangement;
- (struct CGSize)_layoutSize;
- (void)_performDeferredLayoutTransitionCompletion;
- (void)_layoutWithAnimations:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewDidLayoutSubviews;
- (void)updateBarInsetsIfNeeded;
- (_Bool)_usesSeparatorView;
- (void)_getStatusBarStyle:(long long *)arg1 childrenAgreeOnStyle:(_Bool *)arg2;
- (long long)preferredStatusBarStyle;
- (void)_updateStatusBarAppearance;
- (void)setNeedsStatusBarAppearanceUpdate;
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (id)initWithPreferredOnScreenCapacity:(unsigned long long)arg1;

@end

