//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BrowserController, BrowserWindowController, BrowserWindowSourceInfo;

@protocol BrowserWindowControllerObserving <NSObject>
- (void)windowController:(BrowserWindowController *)arg1 didRemoveWindow:(BrowserController *)arg2;
- (void)windowController:(BrowserWindowController *)arg1 didAddWindow:(BrowserController *)arg2 withSourceInfo:(BrowserWindowSourceInfo *)arg3;
@end

