//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BrowserPopoverPresentationDelegate.h"

@interface BrowserToolbarPopoverPresentationDelegate : BrowserPopoverPresentationDelegate
{
    long long _buttonIdentifier;
}

- (id)_browserToolbar;
- (struct CGRect)sourceRect;
- (id)sourceView;
- (id)initWithPopoverPresentationController:(id)arg1 browserController:(id)arg2 buttonIdentifier:(long long)arg3;

@end

