//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CALayer;

@protocol BrowserToolbarDelegate <NSObject>
- (struct CGPoint)targetPointForButtonBarLinkImageAnimationIntoLayer:(CALayer *)arg1 proposedTargetPoint:(struct CGPoint)arg2;
- (void)presentTabExposePopoverFromButtonBar;
- (void)presentForwardPopoverFromButtonBar;
- (void)presentBackPopoverFromButtonBar;
- (void)toggleBookmarksFromButtonBar;
- (void)showTabsFromButtonBar;
- (void)presentBookmarksLongPressMenuFromButtonBar;
- (void)showActionPanelFromButtonBar;
- (void)forwardFromButtonBar;
- (void)backFromButtonBar;

@optional
- (void)presentAddTabPopoverFromButtonBar;
- (void)addTabFromButtonBar;
@end

