//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSURL;

@interface CaptiveLandingPageController : NSObject
{
    NSURL *_captiveLandingPageURL;
    unsigned long long _URLGeneration;
}

+ (id)sharedCaptiveLandingPageController;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURL *captiveLandingPageURL;
- (void)clearCaptiveLandingPageURL;
- (id)popCaptiveLandingPageURL;
- (id)init;

@end

