//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CompletionItemActionHandler-Protocol.h"
#import "CompletionListDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegatePrivate-Protocol.h"
#import "UIPopoverPresentationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UnifiedFieldDelegate-Protocol.h"
#import "UniversalSearchFeedbackDelegate-Protocol.h"
#import "UniversalSearchFirstTimeExperienceViewControllerDelegate-Protocol.h"

@class BookmarksNavigationController, BrowserController, CompletionDetailViewController, CompletionList, CompletionListTableViewController, CompletionsAndFavoritesViewController, NSString, NavigationBar, UIPopoverPresentationController, UIView, UIWindow, UnifiedField, UniversalSearchFirstTimeExperienceViewController, UniversalSearchSession;
@protocol CatalogViewControllerDelegate, CompletionItem;

@interface CatalogViewController : UIViewController <CompletionItemActionHandler, CompletionListDelegate, UITableViewDataSource, UITableViewDelegate, UnifiedFieldDelegate, UniversalSearchFeedbackDelegate, UniversalSearchFirstTimeExperienceViewControllerDelegate, SKStoreProductViewControllerDelegatePrivate, UIPopoverPresentationControllerDelegate>
{
    BrowserController *_browserController;
    CompletionListTableViewController *_completionTableController;
    CompletionsAndFavoritesViewController *_completionsAndFavoritesController;
    UniversalSearchFirstTimeExperienceViewController *_firstTimeExperienceViewController;
    unsigned long long _lastTopHitMatchLength;
    UIPopoverPresentationController *_popoverPresentationController;
    _Bool _dismissingPopover;
    _Bool _completionTableViewStyleUpdated;
    CompletionDetailViewController *_detailViewController;
    _Bool _completionTableIsReloading;
    _Bool _usesPopoverStyleForFavorites;
    _Bool _transitioningToNewSizeClass;
    _Bool _showingCompletions;
    CompletionList *_completionList;
    id <CatalogViewControllerDelegate> _delegate;
    NavigationBar *_navigationBar;
    BookmarksNavigationController *_bookmarksNavigationController;
    UIWindow *_detailWindow;
    UniversalSearchSession *_parsecSearchSession;
    id <CompletionItem> _lastTopHitMatch;
    UnifiedField *_textField;
    struct UIEdgeInsets _obscuredInsets;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
+ (void)updateParsecEnabled;
+ (void)initialize;
@property(retain, nonatomic) UnifiedField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) id <CompletionItem> lastTopHitMatch; // @synthesize lastTopHitMatch=_lastTopHitMatch;
@property(retain, nonatomic) UniversalSearchSession *parsecSearchSession; // @synthesize parsecSearchSession=_parsecSearchSession;
@property(nonatomic, getter=isShowingCompletions) _Bool showingCompletions; // @synthesize showingCompletions=_showingCompletions;
@property(nonatomic, getter=isTransitioningToNewSizeClass) _Bool transitioningToNewSizeClass; // @synthesize transitioningToNewSizeClass=_transitioningToNewSizeClass;
@property(retain, nonatomic) UIWindow *detailWindow; // @synthesize detailWindow=_detailWindow;
@property(readonly, nonatomic) BookmarksNavigationController *bookmarksNavigationController; // @synthesize bookmarksNavigationController=_bookmarksNavigationController;
@property(nonatomic) _Bool usesPopoverStyleForFavorites; // @synthesize usesPopoverStyleForFavorites=_usesPopoverStyleForFavorites;
@property(nonatomic) struct UIEdgeInsets obscuredInsets; // @synthesize obscuredInsets=_obscuredInsets;
@property(retain, nonatomic) NavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(nonatomic) __weak id <CatalogViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CompletionList *completionList; // @synthesize completionList=_completionList;
- (void).cxx_destruct;
- (void)productViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (_Bool)shouldShareSnapshotImage;
- (id)snapshotImageWithSize:(struct CGSize)arg1;
- (double)_statusBarAdjustmentHeightForSnapshotting;
@property(readonly, nonatomic) _Bool isShowingUniversalSearchFirstTimeExperience;
- (void)_dismissUniversalSearchFirstTimeExperience:(id)arg1 dismissalReason:(long long)arg2;
- (void)didCancelUniversalSearchFirstTimeExperienceViewController:(id)arg1;
- (void)didInteractWithUniversalSearchFirstTimeExperienceViewController:(id)arg1;
- (void)dismissCompletionsForSizeClassTransition;
- (void)firstTimeExperienceContinueButtonPressed;
- (void)showUniversalSearchFirstTimeExperienceIfNotShowing;
- (void)feedbackButtonWasTappedWithProblemURL:(id)arg1;
- (void)_unifiedFieldTab:(id)arg1;
- (void)_unifiedFieldReturnKey:(id)arg1;
- (void)_unifiedFieldUpKey:(id)arg1;
- (void)_unifiedFieldDownKey:(id)arg1;
- (_Bool)unifiedField:(id)arg1 canPerformAction:(SEL)arg2 withSender:(id)arg3;
- (void)unifiedField:(id)arg1 registerKeyCommandsUsingBlock:(CDUnknownBlockType)arg2;
- (void)unifiedFieldReflectedItemDidChange:(id)arg1;
- (id)unifiedField:(id)arg1 topHitForText:(id)arg2;
- (_Bool)unifiedField:(id)arg1 shouldWaitForTopHitForText:(id)arg2;
- (void)unifiedField:(id)arg1 didEndEditingWithParsecTopHit:(id)arg2;
- (void)unifiedField:(id)arg1 didEndEditingWithSearch:(id)arg2;
- (void)unifiedField:(id)arg1 didEndEditingWithAddress:(id)arg2;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)resumeSearchWithQuery:(id)arg1;
- (void)dismissCompletions;
@property(readonly, nonatomic, getter=isShowingCompletionDetail) _Bool showingCompletionDetail;
- (void)dismissCompletionDetailWindowAndResumeEditingIfNeeded:(_Bool)arg1;
- (void)presentDetail:(id)arg1;
- (void)findOnPage;
- (void)loadRequest:(id)arg1;
- (void)goToURL:(id)arg1;
- (void)goToURLString:(id)arg1;
- (void)search:(id)arg1;
- (id)browserController;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)_selectedCompletionItemAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableViewDidFinishReload:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)_completionItemAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)completionList:(id)arg1 topHitDidBecomeReadyForString:(id)arg2;
- (void)_logTopHitWasChosen:(_Bool)arg1;
- (void)_generateVisibleResultsFeedbackForIndexPaths:(id)arg1;
- (void)completionListDidUpdate:(id)arg1 forQuery:(id)arg2;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)_textFieldEditingChanged;
- (void)_ensureCompletionListAndParsecSession;
- (void)cancelUnifiedFieldSearch;
- (void)stopCompleting;
- (void)_showCompletionsInPopover;
- (void)_embedCompletionTableControllerIfNeeded;
- (void)_setShowingCompletions:(_Bool)arg1 popoverDismissalReason:(long long)arg2;
- (void)_updateCompletionTableViewStyleIfNeeded;
- (void)resume;
- (void)displayPopover;
- (void)_clearParsecSearchSession;
- (void)_beginParsecSessionIfNeeded;
- (void)_setTextField:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (struct UIEdgeInsets)_obscuredInsetsAdjustedForLayoutDirection;
- (void)traitCollectionDidChange:(id)arg1;
- (void)popoverPresentationController:(id)arg1 willRepositionPopoverToRect:(inout struct CGRect *)arg2 inView:(inout id *)arg3;
- (void)popoverPresentationControllerWillDismissPopover:(id)arg1;
- (void)_popoverDismissCompletion;
- (void)_dismissPopoverAnimated:(_Bool)arg1 dismissalReason:(long long)arg2;
- (long long)adaptivePresentationStyleForPresentationController:(id)arg1 traitCollection:(id)arg2;
- (void)_reloadCompletionTable;
- (void)prepareToTogglePrivateBrowsing:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_presentPopoverWithViewController:(id)arg1;
- (void)loadView;
@property(retain, nonatomic) NSString *queryString;
- (void)resetFavorites;
- (void)loadFavoritesList;
@property(readonly, nonatomic) UIView *favoritesView;
- (void)updateBackgroundColor;
- (id)_favoritesGridView;
@property(readonly, nonatomic) _Bool needsTransparentBackground;
@property(readonly, nonatomic) _Bool popoverIsShowing;
- (void)willMoveToParentViewController:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 bookmarksNavigationController:(id)arg2 browserController:(id)arg3;
- (void)updatePopoverWidth;
- (void)_parsecEnabledDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

