//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CloudTabItemDeleteButton, UIButton;

@interface CloudTabItemDeleteConfirmationView : UIView
{
    CloudTabItemDeleteButton *_deleteButton;
}

@property(readonly, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
- (void).cxx_destruct;
@property(readonly, nonatomic) double defaultWidth;
- (void)layoutSubviews;
- (id)init;

@end

