//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "CompletionProviderDelegate-Protocol.h"
#import "FindOnPageCompletionProviderDataSource-Protocol.h"
#import "SearchSuggestionProviderDelegate-Protocol.h"

@class BrowserController, CompletionListGroup, CompletionProvider, FindOnPageCompletionProvider, NSArray, NSDate, NSMutableDictionary, NSString, NSTimer, QuickWebsiteSearchCompletionProvider, ReadingListCompletionProvider, SearchQueryRestorationCompletionItem, SearchSuggestionProvider, URLCompletionProvider, UniversalSearchCompletionProvider, UniversalSearchSession, WBSCompletionQuery;
@protocol CompletionItem, CompletionListDelegate;

@interface CompletionList : NSObject <CompletionProviderDelegate, FindOnPageCompletionProviderDataSource, SearchSuggestionProviderDelegate>
{
    WBSCompletionQuery *_query;
    unsigned long long _inputTypeOfStringToComplete;
    NSArray *_groups;
    SearchQueryRestorationCompletionItem *_queryRestorationCompletionItem;
    NSMutableDictionary *_rankingFeedbackForHiddenOrDuplicateResults;
    NSDate *_nextAllowedUpdateTime;
    NSDate *_showPartialCompletionsTime;
    NSTimer *_updateTimer;
    CompletionListGroup *_findOnPageGroup;
    NSString *_stringMatchedByTopHit;
    NSString *_matchingStringInTopHit;
    id <CompletionItem> _topHit;
    _Bool _tryParsecRewritesIfNoTopHit;
    WBSCompletionQuery *_rewrittenQuery;
    _Bool _shouldIncludeSearchSuggestions;
    _Bool _networkIsReachable;
    BrowserController *_browserController;
    UniversalSearchSession *_parsecSearchSession;
    id <CompletionListDelegate> _delegate;
    unsigned long long _maximumCompletionsPerGroup;
    URLCompletionProvider *_URLCompletionProvider;
    SearchSuggestionProvider *_suggestionProvider;
    ReadingListCompletionProvider *_readingListProvider;
    FindOnPageCompletionProvider *_findOnPageProvider;
    QuickWebsiteSearchCompletionProvider *_quickWebsiteSearchProvider;
    CompletionProvider *_firstRemoteCompletionProviderToRespondToQuery;
    UniversalSearchCompletionProvider *_universalSearchProvider;
    NSDate *_otherRenderTimeoutStartTime;
    NSDate *_searchRenderTimeoutStartTime;
}

+ (id)completionBookmarkProvider;
@property(retain, nonatomic) NSDate *searchRenderTimeoutStartTime; // @synthesize searchRenderTimeoutStartTime=_searchRenderTimeoutStartTime;
@property(retain, nonatomic) NSDate *otherRenderTimeoutStartTime; // @synthesize otherRenderTimeoutStartTime=_otherRenderTimeoutStartTime;
@property(retain, nonatomic) UniversalSearchCompletionProvider *universalSearchProvider; // @synthesize universalSearchProvider=_universalSearchProvider;
@property(retain, nonatomic) CompletionProvider *firstRemoteCompletionProviderToRespondToQuery; // @synthesize firstRemoteCompletionProviderToRespondToQuery=_firstRemoteCompletionProviderToRespondToQuery;
@property(retain, nonatomic) QuickWebsiteSearchCompletionProvider *quickWebsiteSearchProvider; // @synthesize quickWebsiteSearchProvider=_quickWebsiteSearchProvider;
@property(retain, nonatomic) FindOnPageCompletionProvider *findOnPageProvider; // @synthesize findOnPageProvider=_findOnPageProvider;
@property(retain, nonatomic) ReadingListCompletionProvider *readingListProvider; // @synthesize readingListProvider=_readingListProvider;
@property(retain, nonatomic) SearchSuggestionProvider *suggestionProvider; // @synthesize suggestionProvider=_suggestionProvider;
@property(retain, nonatomic) URLCompletionProvider *URLCompletionProvider; // @synthesize URLCompletionProvider=_URLCompletionProvider;
@property(nonatomic) _Bool networkIsReachable; // @synthesize networkIsReachable=_networkIsReachable;
@property(nonatomic) unsigned long long maximumCompletionsPerGroup; // @synthesize maximumCompletionsPerGroup=_maximumCompletionsPerGroup;
@property(retain, nonatomic) WBSCompletionQuery *query; // @synthesize query=_query;
@property(nonatomic) _Bool shouldIncludeSearchSuggestions; // @synthesize shouldIncludeSearchSuggestions=_shouldIncludeSearchSuggestions;
@property(nonatomic) __weak id <CompletionListDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UniversalSearchSession *parsecSearchSession; // @synthesize parsecSearchSession=_parsecSearchSession;
@property(readonly, nonatomic) __weak BrowserController *browserController; // @synthesize browserController=_browserController;
- (void).cxx_destruct;
- (id)tabDocumentForFindOnPageCompletionProvider:(id)arg1;
- (void)searchSuggestionProviderDidStopConnection:(id)arg1;
- (void)searchSuggestionProviderDidStartConnection:(id)arg1;
- (id)_findOnPageGroupForQuery:(id)arg1;
@property(readonly, nonatomic) unsigned long long findOnPageGroupIndex;
- (void)clearCachedSearches;
- (void)clearCachedSearchQuery;
- (void)didResumeSearch;
- (void)restoreCachedCompletions;
- (void)cacheCurrentCompletionsAfterAcceptanceOfCompletionItem:(id)arg1;
- (void)stopCompleting;
@property(readonly, nonatomic) _Bool hasCompletions;
- (void)configureHeaderView:(id)arg1 forGroupAtIndex:(unsigned long long)arg2;
- (id)headerViewForGroupAtIndex:(unsigned long long)arg1;
- (id)headerViewReuseIdentifierForGroupAtIndex:(unsigned long long)arg1;
- (id)completionsForGroupAtIndex:(unsigned long long)arg1;
- (id)titleForGroupAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfGroups;
- (void)completionProviderDidFail:(id)arg1;
- (void)completionProvider:(id)arg1 didFinishCompletingString:(id)arg2;
- (_Bool)isTopHitReadyForString:(id)arg1;
- (id)topHitForString:(id)arg1;
- (_Bool)_topHitMatchesString:(id)arg1;
- (void)_updateProviders;
- (void)_setNeedsUpdate;
- (void)_scheduleUpdateOnOrBeforeDate:(id)arg1 withCurrentDate:(id)arg2;
- (_Bool)_searchRenderTimeoutHasElapsed;
- (void)_updateTimerFired:(id)arg1;
- (void)_update;
- (void)_invalidateUpdateTimer;
- (_Bool)_urlString:(id)arg1 isProbablyContainedIn:(id)arg2;
- (void)_searchForURLTopHits:(id)arg1 intoTopHits:(id)arg2 andAddresses:(id)arg3;
- (void)_addTopHits:(id)arg1 intoGroups:(id)arg2;
- (void)_addResult:(id)arg1 intoGroup:(id)arg2 unlessHiddenBy:(id)arg3 topHit:(id)arg4;
- (void)_addResults:(id)arg1 intoGroups:(id)arg2;
- (id)_groupsForQuery:(id)arg1 allowPartialCompletions:(_Bool)arg2 findOnPageGroup:(id *)arg3 topHit:(id *)arg4 topHitReady:(_Bool *)arg5;
- (_Bool)_shouldFetchSearchSuggestions;
- (void)_removeCompletionsWithAddressInSet:(id)arg1 fromArray:(id)arg2 andTruncateTo:(unsigned long long)arg3;
- (id)_groupsOnUnreachableNetworkForString:(id)arg1;
- (void)_removeSearchURLsFromCompletions:(id)arg1;
- (id)_groupWithTitle:(id)arg1 completions:(id)arg2;
- (id)_groupWithTitle:(id)arg1 completions:(id)arg2 maximumCompletions:(unsigned long long)arg3;
- (id)_titleForFindOnPageHeaderWithMatchCount:(unsigned long long)arg1;
- (id)_completionsByMergingRecentSearches:(id)arg1 withSuggestions:(id)arg2 andLiteralSearch:(id)arg3;
- (id)_recentSearchesForString:(id)arg1;
- (void)dealloc;
- (id)initWithParsecSearchSession:(id)arg1 browserController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

