//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBSCompletionListItem-Protocol.h"

@class CompletionList, NSString, UITableViewCell, UIView;
@protocol CompletionItemActionHandler;

@protocol CompletionItem <WBSCompletionListItem>
- (NSString *)reflectedStringForUserTypedString:(NSString *)arg1;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;
- (void)acceptCompletionWithActionHandler:(id <CompletionItemActionHandler>)arg1;
- (void)configureCompletionTableViewCell:(UITableViewCell *)arg1 forCompletionList:(CompletionList *)arg2;
- (UITableViewCell *)completionTableViewCellForCompletionList:(CompletionList *)arg1;
- (NSString *)completionTableViewCellReuseIdentifier;

@optional
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
@property(readonly, nonatomic) _Bool restoresSearchState;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
@property(copy, nonatomic) NSString *completionString;
- (NSString *)userVisibleURLString;
- (NSString *)originalURLString;
- (_Bool)shouldPrefetchWithMatchLength:(unsigned long long)arg1;
- (void)configureCompletionTableHeaderView:(UIView *)arg1 forCompletionList:(CompletionList *)arg2;
- (UIView *)completionTableHeaderView;
- (double)completionTableViewCellCustomHeightForCompletionList:(CompletionList *)arg1;
@end

