//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BrowserController, NSString, NSURL, NSURLRequest, UIViewController, WBSCompletionQuery;

@protocol CompletionItemActionHandler <NSObject>
- (BrowserController *)browserController;
- (void)loadRequest:(NSURLRequest *)arg1;
- (void)resumeSearchWithQuery:(WBSCompletionQuery *)arg1;
- (void)dismissCompletions;
- (void)presentDetail:(UIViewController *)arg1;
- (void)findOnPage;
- (void)goToURL:(NSURL *)arg1;
- (void)goToURLString:(NSString *)arg1;
- (void)search:(NSString *)arg1;
@end

