//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchFoundation/SFResultSection.h>

@class NSArray, NSString;

@interface CompletionListGroup : SFResultSection
{
    NSString *_headerViewReuseIdentifier;
    NSArray *_completions;
}

@property(readonly, copy, nonatomic) NSArray *completions; // @synthesize completions=_completions;
@property(readonly, copy, nonatomic) NSString *headerViewReuseIdentifier; // @synthesize headerViewReuseIdentifier=_headerViewReuseIdentifier;
- (void).cxx_destruct;
- (void)setCompletions:(id)arg1;
- (void)configureHeaderView:(id)arg1 forCompletionList:(id)arg2;
- (id)headerView;
- (id)initWithTitle:(id)arg1 completions:(id)arg2 maximumNumberOfCompletions:(unsigned long long)arg3;

@end

