//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ContinuousReadingItem, TabController, WBSAutomaticReadingListItem;

@interface ContinuousReadingController : NSObject
{
    TabController *_tabController;
    int _activeDocumentBookmarkID;
    WBSAutomaticReadingListItem *_activeDocumentAutomaticItem;
    ContinuousReadingItem *_currentContinuousItem;
    ContinuousReadingItem *_nextContinuousItem;
    ContinuousReadingItem *_previousContinuousItem;
    _Bool _unreadReadingListItemsOnly;
}

@property(nonatomic) _Bool unreadReadingListItemsOnly; // @synthesize unreadReadingListItemsOnly=_unreadReadingListItemsOnly;
- (void).cxx_destruct;
- (id)_nextAutomaticReadingListItemInItems:(id)arg1;
- (id)_previousAutomaticReadingListItemInItems:(id)arg1;
- (id)_itemAtIndex:(unsigned int)arg1 inReadingList:(id)arg2;
- (void)_updateCachedItemsIfNeeded;
- (void)_clearCachedItems;
- (id)_tabDocument;
- (id)previousReadingListItem;
- (id)nextReadingListItem;
- (id)currentReadingListItem;
- (void)dealloc;
- (id)initWithTabController:(id)arg1;

@end

