//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIView;

@interface DragOverlayViewController : UIViewController
{
    struct CGPoint _draggingViewCenterPoint;
    UIView *_sourceView;
    UIView *_draggingView;
}

@property(readonly, nonatomic) UIView *draggingView; // @synthesize draggingView=_draggingView;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)updateInteractionWithPoint:(struct CGPoint)arg1;
- (void)beginInteractionWithSourceView:(id)arg1 startPoint:(struct CGPoint)arg2;

@end

