//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebUI/WBUFeatureManager.h>

@interface FeatureManager : WBUFeatureManager
{
    _Bool _addToHomeScreenAvailable;
    _Bool _webFeedSubscriptionsAvailable;
}

+ (id)sharedFeatureManager;
@property(readonly, nonatomic, getter=isWebFeedSubscriptionsAvailable) _Bool webFeedSubscriptionsAvailable; // @synthesize webFeedSubscriptionsAvailable=_webFeedSubscriptionsAvailable;
@property(readonly, nonatomic, getter=isAddToHomeScreenAvailable) _Bool addToHomeScreenAvailable; // @synthesize addToHomeScreenAvailable=_addToHomeScreenAvailable;
- (void)_updateAccessLevel;
- (id)init;

@end

