//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "BookmarksPanelStateRestoring-Protocol.h"
#import "BookmarksToolbarItemProvider-Protocol.h"
#import "HistoryTableViewDataSourceDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class HistoryTableViewDataSource, NSString, NSTimer, SafariClearBrowsingDataController, UIBarButtonItem;
@protocol HistoryTableViewControllerDelegate;

@interface HistoryTableViewController : UITableViewController <BookmarksToolbarItemProvider, HistoryTableViewDataSourceDelegate, UISearchBarDelegate, BookmarksPanelStateRestoring>
{
    UIBarButtonItem *_clearHistoryButton;
    UIBarButtonItem *_doneBarButtonItem;
    NSTimer *_saveChangesToCloudHistoryTimer;
    SafariClearBrowsingDataController *_clearDataController;
    HistoryTableViewDataSource *_historyDataSource;
    _Bool _needsInitialContentOffsetUpdateForTableHeaderView;
    _Bool _needsContentOffsetUpdate;
    id <HistoryTableViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <HistoryTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)historyTableViewDataSource:(id)arg1 didChangeRowAtIndexPath:(id)arg2 forChangeType:(long long)arg3;
- (void)historyTableViewDataSource:(id)arg1 didChangeSectionAtIndex:(long long)arg2 forChangeType:(long long)arg3;
- (void)historyTableViewDataSourceDidChangeContent:(id)arg1;
- (void)historyTableViewDataSourceWillChangeContent:(id)arg1;
- (void)historyTableViewDataSourceDidLoadContent:(id)arg1;
- (id)safari_tableViewScrollPositionSaveIdentifier;
@property(readonly, nonatomic) NSString *collectionType;
- (void)restoreScrollPosition:(double)arg1;
- (double)currentScrollPosition;
- (_Bool)restoreStateWithDictionary:(id)arg1;
- (id)currentStateDictionary;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)_saveChangesToCloudHistory;
- (void)_saveChangesToCloudHistorySoon;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateContentOffsetIfNeeded;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_endEditing;
- (void)_clearHistory;
- (id)_clearHistoryAlertMessage;
- (void)updateClearHistoryButtonEnable;
- (id)_clearHistoryBarButtonItem;
- (id)_doneBarButtonItem;
- (id)bookmarksRightBarButtonItem;
- (id)bookmarksNavigationController;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

