//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSOrderedSet, NSString;

@interface HistoryTableViewDataSourceSession : NSObject
{
    NSString *_sessionIdentifier;
    NSDate *_sessionDate;
    NSOrderedSet *_historyItems;
}

+ (id)_sessionIdentifierFromDate:(id)arg1;
+ (id)_sessionDateFromDate:(id)arg1;
+ (id)sessionIdentifierFromDate:(id)arg1;
+ (id)sessionWithDate:(id)arg1;
+ (void)initialize;
@property(copy, nonatomic) NSOrderedSet *historyItems; // @synthesize historyItems=_historyItems;
@property(readonly, nonatomic) NSDate *sessionDate; // @synthesize sessionDate=_sessionDate;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *sessionIdentifier;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithDate:(id)arg1;

@end

