//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class _WKVisitedLinkProvider;

@interface HistoryController : NSObject
{
    _WKVisitedLinkProvider *_visitedLinkProvider;
}

+ (id)sharedHistoryController;
- (void).cxx_destruct;
@property(readonly, nonatomic) _WKVisitedLinkProvider *visitedLinkProvider;
- (id)init;

@end

