//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSURL, WBSAutomaticReadingListItem, WBSCloudTab, WebBookmark;

@interface NavigationDestination : NSObject
{
    unsigned long long _type;
    WebBookmark *_bookmark;
    WBSCloudTab *_cloudTab;
    WBSAutomaticReadingListItem *_automaticReadingListItem;
    NSURL *_URL;
}

+ (id)navigationDestinationWithSocialProfileURL:(id)arg1;
+ (id)navigationDestinationWithAutomaticReadingListItem:(id)arg1;
+ (id)navigationDestinationWithHistoryURL:(id)arg1;
+ (id)navigationDestinationWithCloudTab:(id)arg1;
+ (id)navigationDestinationWithBookmark:(id)arg1;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) WBSAutomaticReadingListItem *automaticReadingListItem; // @synthesize automaticReadingListItem=_automaticReadingListItem;
@property(retain, nonatomic) WBSCloudTab *cloudTab; // @synthesize cloudTab=_cloudTab;
@property(retain, nonatomic) WebBookmark *bookmark; // @synthesize bookmark=_bookmark;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (id)_initWithType:(unsigned long long)arg1;

@end

