//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@protocol LinkPreviewProvider, PreviewTableViewControllerDelegate;

@interface PreviewTableViewController : UITableViewController
{
    id <PreviewTableViewControllerDelegate> _previewDelegate;
    id <LinkPreviewProvider> _linkPreviewProvider;
}

@property(nonatomic) __weak id <LinkPreviewProvider> linkPreviewProvider; // @synthesize linkPreviewProvider=_linkPreviewProvider;
@property(nonatomic) __weak id <PreviewTableViewControllerDelegate> previewDelegate; // @synthesize previewDelegate=_previewDelegate;
- (void).cxx_destruct;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)commitPreviewViewController:(id)arg1;
- (id)previewViewControllerForRowAtIndexPath:(id)arg1;
- (void)viewDidLoad;

@end

