//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "QLContentView-Protocol.h"

@class NSString, OpenInApplicationBarButtonItem, QLDocumentInfoView, UIBarButtonItem, UIToolbar;

@interface QLContentViewIPad : UIImageView <QLContentView>
{
    QLDocumentInfoView *_documentInfoView;
    UIToolbar *_buttonBar;
    OpenInApplicationBarButtonItem *_defaultApplicationButtonItem;
    UIBarButtonItem *_otherApplicationsButtonItem;
}

- (void).cxx_destruct;
- (void)updateWithQuickLookDocument:(id)arg1;
- (void)_updateOtherApplicationsButtonItem;
- (void)_updateDefaultApplicationButtonItem:(id)arg1 multipleApplications:(_Bool)arg2;
- (void)layoutSubviews;
- (void)showBanner;
- (void)hideBanner;
- (id)initWithFrame:(struct CGRect)arg1 tabDocument:(id)arg2 quickLookBannerViewDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

