//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol QLContentView;

@interface QuickLookDocumentView : UIView
{
    UIView<QLContentView> *_contentView;
}

- (void).cxx_destruct;
- (void)updateWithQuickLookDocument:(id)arg1;
- (void)showBanner;
- (void)hideBanner;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 tabDocument:(id)arg2 quickLookBannerViewDelegate:(id)arg3;

@end

