//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@class OpenInApplicationBarButtonItem, TabDocument, UIBarButtonItem, UILabel;
@protocol QuickLookBannerViewDelegate;

@interface QuickLookBannerView : UIToolbar
{
    UILabel *_filenameLabel;
    UIBarButtonItem *_flexibleSpaceItem;
    OpenInApplicationBarButtonItem *_openInApplicationItem;
    UIBarButtonItem *_openInOtherApplicationsItem;
    TabDocument *_tabDocument;
}

- (void).cxx_destruct;
- (void)animateOut;
- (void)animateIn;
- (void)_animateTo:(double)arg1;
- (_Bool)updateWithQuickLookDocument:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_layoutFilenameLabel;
@property(nonatomic) __weak id <QuickLookBannerViewDelegate> quickLookDelegate;
- (id)initWithTabDocument:(id)arg1 quickLookBannerViewDelegate:(id)arg2;

@end

