//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CADisplayLink;

@interface ReorderingAutoscroller : NSObject
{
    CADisplayLink *_displayLink;
    struct CGPoint _offsetError;
    CDUnknownBlockType _scrollHandler;
    struct CGPoint _velocity;
    double _maximumSpeed;
    struct CGRect _scrollableRect;
    struct UIEdgeInsets _autoscrollInsets;
}

@property(nonatomic) double maximumSpeed; // @synthesize maximumSpeed=_maximumSpeed;
@property(nonatomic) struct UIEdgeInsets autoscrollInsets; // @synthesize autoscrollInsets=_autoscrollInsets;
@property(nonatomic) struct CGRect scrollableRect; // @synthesize scrollableRect=_scrollableRect;
- (void).cxx_destruct;
- (void)_autoscroll:(id)arg1;
- (void)_setVelocity:(struct CGPoint)arg1;
- (void)endInteraction;
- (void)updateInteractionAtPoint:(struct CGPoint)arg1;
- (void)beginInteractionWithScrollHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

