//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CompletionProviderDelegate-Protocol.h"

@class SearchSuggestionProvider;

@protocol SearchSuggestionProviderDelegate <CompletionProviderDelegate>

@optional
- (void)searchSuggestionProviderDidStopConnection:(SearchSuggestionProvider *)arg1;
- (void)searchSuggestionProviderDidStartConnection:(SearchSuggestionProvider *)arg1;
@end

