//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "CompletionItem-Protocol.h"

@class NSString, SFSearchResult;
@protocol CompletionItemActionHandler;

@interface SearchSuggestion : NSObject <CompletionItem>
{
    _Bool _recentSearch;
    _Bool _searchEngineSuggestion;
    SFSearchResult *_sfSearchResultValue;
    _Bool _goesToURL;
    NSString *_string;
}

@property(nonatomic) _Bool goesToURL; // @synthesize goesToURL=_goesToURL;
@property(readonly, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long engagementDestination;
@property(readonly, nonatomic) SFSearchResult *sfSearchResultValue;
- (id)reflectedStringForUserTypedString:(id)arg1;
@property(readonly, nonatomic) _Bool restoresSearchState;
@property(readonly, nonatomic) NSString *parsecDomainIdentifier;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;
- (double)completionTableViewCellCustomHeightForCompletionList:(id)arg1;
- (id)completionTableViewCellForCompletionList:(id)arg1;
- (id)completionTableViewCellReuseIdentifier;
- (void)acceptCompletionWithActionHandler:(id)arg1;
- (void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;
@property(readonly, copy) NSString *description;
- (id)initWithSearchEngineSuggestion:(id)arg1;
- (id)initWithRecentSearchString:(id)arg1;
- (id)initWithUserTypedString:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *completionString;
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *lastSearchQuery;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly) Class superclass;

@end

