//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class _SFReaderAppearanceViewController;

@protocol SFReaderAppearanceViewControllerDelegate <NSObject>
- (void)readerAppearanceViewControllerDidChangeTheme:(_SFReaderAppearanceViewController *)arg1;
- (void)readerAppearanceViewControllerDidDecreaseTextSize:(_SFReaderAppearanceViewController *)arg1;
- (void)readerAppearanceViewControllerDidIncreaseTextSize:(_SFReaderAppearanceViewController *)arg1;
- (void)readerAppearanceViewControllerDidChangeFont:(_SFReaderAppearanceViewController *)arg1;
@end

