//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class ACAccount, NSURL, SharedLinksSubscriptionsViewController, UIImage;

@protocol SharedLinksSubscriptionsViewControllerDelegate
- (UIImage *)sharedLinksSubscriptionsViewControllerServiceIconForAccount:(ACAccount *)arg1;
- (void)sharedLinksSubscriptionsViewControllerSubscribeToCurrentWebFeed:(SharedLinksSubscriptionsViewController *)arg1;
- (NSURL *)sharedLinksSubscriptionsViewControllerCurrentWebFeedURL:(SharedLinksSubscriptionsViewController *)arg1;
@end

