//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate;
@protocol SidebarInteractionReporterDelegate;

@interface SidebarInteractionReporter : NSObject
{
    NSDate *_lastSidebarSelectionDate;
    id <SidebarInteractionReporterDelegate> _delegate;
}

@property(nonatomic) __weak id <SidebarInteractionReporterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reportUserClosedSidebar;
- (void)reportUserSelectedFromSidebarSection:(long long)arg1;
- (_Bool)_shouldReportEventsForCurrentApplicationState;
- (id)initWithDelegate:(id)arg1;

@end

