//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class SocialLinksTableViewCell, UIImage, WBSAutomaticReadingListItem;

@protocol SocialLinksTableViewCellDelegate
- (void)socialLinksTableViewCellProfilePictureWasTapped:(SocialLinksTableViewCell *)arg1;
- (UIImage *)socialLinksTableViewCell:(SocialLinksTableViewCell *)arg1 serviceImageForReadingListItem:(WBSAutomaticReadingListItem *)arg2;
@end

