//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, TabBar, TabBarItemLayoutInfo;

@interface TabBarItem : NSObject
{
    _Bool _active;
    _Bool _isPlaceholder;
    NSString *_title;
    TabBar *_tabBar;
    TabBarItemLayoutInfo *_layoutInfo;
}

@property(retain, nonatomic) TabBarItemLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(retain, nonatomic) TabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(nonatomic) _Bool isPlaceholder; // @synthesize isPlaceholder=_isPlaceholder;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

