//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class TabBar, TabBarItem;

@protocol TabBarDelegate
- (void)tabBar:(TabBar *)arg1 didEndDragInteractionAtPoint:(struct CGPoint)arg2;
- (void)tabBar:(TabBar *)arg1 didUpdateDragInteractionPoint:(struct CGPoint)arg2;
- (void)tabBar:(TabBar *)arg1 didBeginDragInteractionForTabBarItem:(TabBarItem *)arg2 atPoint:(struct CGPoint)arg3 dragType:(long long)arg4;
- (_Bool)tabBar:(TabBar *)arg1 canBeginDragInteractionForTabBarItem:(TabBarItem *)arg2;
- (void)tabBar:(TabBar *)arg1 closeItem:(TabBarItem *)arg2;
- (void)tabBar:(TabBar *)arg1 activateItem:(TabBarItem *)arg2;
- (void)tabBar:(TabBar *)arg1 moveItem:(TabBarItem *)arg2 overItem:(TabBarItem *)arg3;
- (_Bool)tabBar:(TabBar *)arg1 canCloseItem:(TabBarItem *)arg2;
- (_Bool)tabBar:(TabBar *)arg1 canMoveItem:(TabBarItem *)arg2;
@end

