//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TabBarItemView, TabOverviewItemView, _UIBackdropView;

@interface TabDragView : UIView
{
    double _tabHeight;
    _UIBackdropView *_backdropView;
    _Bool _hasDarkBackground;
    TabBarItemView *_tabBarItemView;
    TabOverviewItemView *_tabOverviewItemView;
    unsigned long long _presentationType;
    struct CGSize _contentsSize;
}

@property(nonatomic) unsigned long long presentationType; // @synthesize presentationType=_presentationType;
@property(nonatomic) _Bool hasDarkBackground; // @synthesize hasDarkBackground=_hasDarkBackground;
@property(nonatomic) struct CGSize contentsSize; // @synthesize contentsSize=_contentsSize;
@property(readonly, nonatomic) TabOverviewItemView *tabOverviewItemView; // @synthesize tabOverviewItemView=_tabOverviewItemView;
@property(readonly, nonatomic) TabBarItemView *tabBarItemView; // @synthesize tabBarItemView=_tabBarItemView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_updatePresentationType;
- (id)initWithTabBar:(id)arg1;

@end

