//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, TabOverview, TabOverviewItemLayoutInfo, TabStackTitleView, UIColor;

@interface TabOverviewItem : NSObject
{
    _Bool _hidden;
    _Bool _closing;
    NSString *_title;
    UIColor *_titleColor;
    NSString *_stackName;
    TabOverviewItemLayoutInfo *_layoutInfo;
    TabStackTitleView *_stackTitleView;
    TabOverview *_tabOverview;
}

@property(nonatomic) __weak TabOverview *tabOverview; // @synthesize tabOverview=_tabOverview;
@property(retain, nonatomic) TabStackTitleView *stackTitleView; // @synthesize stackTitleView=_stackTitleView;
@property(retain, nonatomic) TabOverviewItemLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) _Bool closing; // @synthesize closing=_closing;
@property(copy, nonatomic) NSString *stackName; // @synthesize stackName=_stackName;
@property(copy, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
- (void).cxx_destruct;

@end

