//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TabThumbnailView.h"

@class UIImageView, UIView;

@interface TabOverviewItemView : TabThumbnailView
{
    double _topBackdropHeight;
    UIView *_snapshotClipperView;
    UIImageView *_snapshotView;
    UIView *_dimmingView;
    struct CGSize _windowSize;
}

@property(retain, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
@property(retain, nonatomic) UIImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) UIView *snapshotClipperView; // @synthesize snapshotClipperView=_snapshotClipperView;
@property(nonatomic) struct CGSize windowSize; // @synthesize windowSize=_windowSize;
@property(nonatomic) double topBackdropHeight; // @synthesize topBackdropHeight=_topBackdropHeight;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateSnapshotWithImage:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithImage:(id)arg1;

@end

