//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSOrderedSet;

@interface TabSnapshotCacheContext : NSObject
{
    _Bool _updating;
    NSOrderedSet *_identifiersToCache;
    unsigned long long _capacity;
}

@property(nonatomic) unsigned long long capacity; // @synthesize capacity=_capacity;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(retain, nonatomic) NSOrderedSet *identifiersToCache; // @synthesize identifiersToCache=_identifiersToCache;
- (void).cxx_destruct;
- (id)description;

@end

