//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMapTable, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface TabSnapshotCache : NSObject
{
    NSMapTable *_delegateToContextMap;
    unsigned long long _currentlyRequestedSnapshotCount;
    NSMutableDictionary *_snapshots;
    _Bool _updating;
    NSString *_thumbnailCacheDirectoryPath;
    NSObject<OS_dispatch_queue> *_fileSystemAccessQueue;
    _Bool _currentlyRequestingNextSnapshot;
    _Bool _needsRequestNextSnapshot;
}

+ (unsigned long long)maximumSnapshotCacheCapacity;
+ (void)removeSavedSnapshotsKeepingSnapshotsWithIdentifiers:(id)arg1;
+ (id)defaultSnapshotCache;
+ (void)initialize;
- (void).cxx_destruct;
- (void)setCapacity:(unsigned long long)arg1 forDelegate:(id)arg2;
- (void)setUpdating:(_Bool)arg1 forDelegate:(id)arg2;
- (id)_contextForDelegate:(id)arg1;
- (void)_sendDidFinishUpdatingToDelegateIfNeeded;
@property(readonly, nonatomic, getter=isFinishedUpdating) _Bool finishedUpdating;
- (void)_requestNextSnapshotIfNecessary;
- (void)_requestNextSnapshotIfNecessaryForDelegate:(id)arg1;
- (id)debugDescription;
- (void)_finishUpdatingToState:(long long)arg1 cachedSnapshot:(id)arg2 forIdentifier:(id)arg3;
- (void)_finishUpdatingToState:(long long)arg1 forIdentifier:(id)arg2;
- (void)_beginUpdatingStateForIdentifier:(id)arg1;
- (void)_saveSnapshotForIdentifier:(id)arg1;
- (void)_requestSavedSnapshotForIdentifier:(id)arg1;
- (void)_determineInitialStateForIdentifier:(id)arg1;
- (void)invalidateSnapshotWithIdentifier:(id)arg1;
- (_Bool)hasValidSnapshotWithIdentifier:(id)arg1;
- (id)snapshotWithIdentifier:(id)arg1;
- (void)setIdentifiersToCache:(id)arg1 forDelegate:(id)arg2;
- (id)identifiersToCacheForDelegate:(id)arg1;
- (id)_allIdentifiersToCache;
- (id)_pathForSavedSnapshotWithIdentifier:(id)arg1;
- (id)_pathForSavedPNGSnapshotWithIdentifier:(id)arg1;
- (id)_pathForSavedSnapshotWithIdentifier:(id)arg1 extension:(id)arg2;
- (void)_didReceiveMemoryWarning:(id)arg1;
- (void)dealloc;
- (id)init;
@property(copy, nonatomic) NSString *thumbnailCacheDirectoryPath;

@end

