//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSObject, NSString, UIButton, UIColor, UIFont, UILabel;
@protocol OS_dispatch_queue;

@interface TabThumbnailView : UIView
{
    UIView *_headerView;
    UILabel *_titleLabel;
    NSObject<OS_dispatch_queue> *_titleMeasurementQueue;
    struct CGSize _titleSize;
    _Bool _titleTextNeedsUpdate;
    UIButton *_closeButton;
    double _extraTitleScale;
    NSString *_title;
    double _titleHeight;
    double _titleOffset;
    double _titleScale;
    double _verticalTextAlignmentAdjustment;
    CDUnknownBlockType _layoutAnimator;
}

@property(copy, nonatomic) CDUnknownBlockType layoutAnimator; // @synthesize layoutAnimator=_layoutAnimator;
@property(nonatomic) double verticalTextAlignmentAdjustment; // @synthesize verticalTextAlignmentAdjustment=_verticalTextAlignmentAdjustment;
@property(nonatomic) double titleScale; // @synthesize titleScale=_titleScale;
@property(nonatomic) double titleOffset; // @synthesize titleOffset=_titleOffset;
@property(nonatomic) double titleHeight; // @synthesize titleHeight=_titleHeight;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double extraTitleScale; // @synthesize extraTitleScale=_extraTitleScale;
@property(readonly, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
- (void).cxx_destruct;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
@property(retain, nonatomic) UIFont *titleFont;
@property(copy, nonatomic) UIColor *titleColor;
@property(nonatomic) double titleAlpha;
- (void)_measureTitle;
@property(nonatomic) _Bool showsCloseButton;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

