//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TabThumbnailView.h"

@class GradientView, TiltedTabSnapshotView, UIView;

@interface TiltedTabThumbnailView : TabThumbnailView
{
    TiltedTabSnapshotView *_snapshotView;
    GradientView *_contentShadowView;
    UIView *_contentClipperView;
    struct CGRect _snapshotFrame;
}

@property(nonatomic) struct CGRect snapshotFrame; // @synthesize snapshotFrame=_snapshotFrame;
@property(readonly, nonatomic) UIView *contentClipperView; // @synthesize contentClipperView=_contentClipperView;
@property(readonly, nonatomic) GradientView *contentShadowView; // @synthesize contentShadowView=_contentShadowView;
- (void).cxx_destruct;
- (void)setSnapshot:(id)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)reset;
- (id)init;

@end

