//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKeyCommand.h>

@interface UIKeyCommand (SafariExtras)
+ (id)safari_keyCommandForAction:(SEL)arg1 fromDictionary:(id)arg2 discoverabilityTitle:(id)arg3;
+ (id)safari_keyCommandForAction:(SEL)arg1 fromDictionary:(id)arg2;
@end

