//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface UITableViewCell (SafariExtras)
+ (double)safari_defaultHeightOfTrivialInstance;
- (void)safari_setLinkedPageTitle:(id)arg1 URL:(id)arg2;
- (void)safari_setLinkedPageTitle:(id)arg1 URL:(id)arg2 simplificationOptions:(unsigned long long)arg3;
@end

