//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (SafariExtras)
- (void)safari_updateApplicationBackgroundStyle;
@property(readonly, nonatomic) _Bool safari_wantsTransparentApplicationBackground;
- (_Bool)safari_isHorizontallyConstrainedFallingBackToRootViewControllerIfNecessary;
- (_Bool)safari_isHorizontallyConstrained;
@end

