//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SearchUIFirstTimeExperienceDelegate-Protocol.h"

@class BrowserController, NSString, SearchUIFirstTimeExperienceViewController;
@protocol UniversalSearchFirstTimeExperienceViewControllerDelegate;

@interface UniversalSearchFirstTimeExperienceViewController : UIViewController <SearchUIFirstTimeExperienceDelegate>
{
    BrowserController *_browserController;
    SearchUIFirstTimeExperienceViewController *_firstTimeExperienceViewController;
    _Bool _navigationBarVisibilityForRestore;
    id <UniversalSearchFirstTimeExperienceViewControllerDelegate> _delegate;
}

+ (void)userDidInteractWithParsecFirstTimeUserExperience;
+ (_Bool)hasShownParsecFirstTimeUserExperience;
@property(nonatomic) _Bool navigationBarVisibilityForRestore; // @synthesize navigationBarVisibilityForRestore=_navigationBarVisibilityForRestore;
@property(nonatomic) __weak id <UniversalSearchFirstTimeExperienceViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)firstTimeExperienceContinueButtonPressed;
- (void)unifiedFieldDidChange;
- (void)viewDidLoad;
- (id)initWithSession:(id)arg1 browserController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

