//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebUI/WBSURLCompletionDatabase.h>

#import "WBSURLCompletionDataSource-Protocol.h"

@class CloudTabStore, NSArray, NSCache, NSObject, NSString;
@protocol OS_dispatch_queue, WBBookmarkProvider;

@interface URLCompletionDatabase : WBSURLCompletionDatabase <WBSURLCompletionDataSource>
{
    CloudTabStore *_cloudTabStore;
    NSArray *_cloudDevices;
    NSObject<OS_dispatch_queue> *_cloudTabsAccessQueue;
    NSCache *_bookmarksCache;
    id <WBBookmarkProvider> _bookmarkProvider;
    int _searchableCollectionsMask;
}

@property(nonatomic) int searchableCollectionsMask; // @synthesize searchableCollectionsMask=_searchableCollectionsMask;
- (void).cxx_destruct;
- (id)fakeBookmarkMatchDataWithURLString:(id)arg1 title:(id)arg2;
- (void)enumerateMatchDataForTypedStringHint:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)_updateCloudDevices:(id)arg1;
- (void)clearBookmarksCache;
- (void)dealloc;
- (id)initWithCloudTabStore:(id)arg1 searchableCollectionsMask:(int)arg2 bookmarkProvider:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

