//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface VibrantSeparatorView : UIView
{
    UIView *_colorBurn;
    UIView *_plusD;
    _Bool _usesVibrantEffect;
    UIColor *_nonVibrantColor;
}

@property(retain, nonatomic) UIColor *nonVibrantColor; // @synthesize nonVibrantColor=_nonVibrantColor;
@property(nonatomic) _Bool usesVibrantEffect; // @synthesize usesVibrantEffect=_usesVibrantEffect;
- (void).cxx_destruct;

@end

