//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIResponder;

@interface ViewWithCustomNextResponder : UIView
{
    UIResponder *_customNextResponder;
}

@property(nonatomic) __weak UIResponder *customNextResponder; // @synthesize customNextResponder=_customNextResponder;
- (void).cxx_destruct;
- (id)nextResponder;

@end

