//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebUI/WBSURLCompletionMatch.h>

#import "CompletionItem-Protocol.h"

@class NSString, SFSearchResult;
@protocol CompletionItemActionHandler;

@interface WBSURLCompletionMatch (SafariCompletionItem) <CompletionItem>
- (id)reflectedStringForUserTypedString:(id)arg1;
- (void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;
- (double)completionTableViewCellCustomHeightForCompletionList:(id)arg1;
- (id)completionTableViewCellForCompletionList:(id)arg1;
- (id)completionTableViewCellReuseIdentifier;
- (void)acceptCompletionWithActionHandler:(id)arg1;
- (void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;

// Remaining properties
@property(copy, nonatomic) NSString *completionString;
@property(readonly, nonatomic) NSString *completionTableHeaderViewReuseIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) unsigned long long engagementDestination;
@property(retain, nonatomic) id <CompletionItemActionHandler> handlerForActionItem;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *lastSearchQuery;
@property(nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult;
@property(readonly, nonatomic) NSString *parsecDomainIdentifier;
@property(readonly, nonatomic) _Bool restoresSearchState;
@property(readonly, nonatomic) SFSearchResult *sfSearchResultValue;
@property(readonly) Class superclass;
@end

