//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKBackForwardListItem.h>

@class NSString, _SFQuickLookDocument;

@interface WKBackForwardListItem (SafariExtras)
@property(nonatomic, setter=safari_setNavigationSnapshotRequiresBars:) _Bool safari_navigationSnapshotRequiresBars;
@property(retain, nonatomic, setter=safari_setQuickLookDocument:) _SFQuickLookDocument *safari_quickLookDocument;
@property(copy, nonatomic, setter=safari_setSharedLinkUniqueIdentifier:) NSString *safari_sharedLinkUniqueIdentifier;
@property(nonatomic, setter=safari_setBookmarkID:) int safari_bookmarkID;
@end

