//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSetupManager : NSObject
{
    _Bool _inSetupMode;
    _Bool _fromOTASoftwareUpdate;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool fromOTASoftwareUpdate; // @synthesize fromOTASoftwareUpdate=_fromOTASoftwareUpdate;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (void)postLaunchCompleteNotificationForSetup;
- (void)showSetupLogoForSetupLaunch;
- (_Bool)setupIsRunningForUpdateInstall;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

@end

