//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ControlCenterUI/CCUIControlCenterSectionView.h>

@interface CCUIBrightnessContentView : CCUIControlCenterSectionView
{
    _Bool _usesCompactHeight;
}

@property(nonatomic) _Bool usesCompactHeight; // @synthesize usesCompactHeight=_usesCompactHeight;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct UIEdgeInsets)layoutMargins;
- (struct CGSize)intrinsicContentSize;

@end

