/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NCNotificationAction;

@interface _NCActionButtonDescription : NSObject {

	NSString* _selectorString;
	NCNotificationAction* _notificationAction;
	NSString* _title;

}

@property (nonatomic,readonly) NCNotificationAction * notificationAction;              //@synthesize notificationAction=_notificationAction - In the implementation block
@property (nonatomic,copy,readonly) NSString * title;                                  //@synthesize title=_title - In the implementation block
@property (nonatomic,readonly) SEL selector; 
-(NSString *)title;
-(SEL)selector;
-(NCNotificationAction *)notificationAction;
-(id)initWithNotificationAction:(id)arg1 ;
-(id)initWithTitle:(id)arg1 selector:(SEL)arg2 ;
@end

