/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, UIImageView;

@interface _NCShortLookSnapshotView : UIView {

	UIView* _clippingView;
	UIImageView* _shadowView;

}
-(void)layoutSubviews;
-(id)initWithSourceView:(id)arg1 andShadow:(BOOL)arg2 ;
@end

