/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:10 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NCAudioPlayerControllerDelegate <NSObject>
@optional
-(void)playerController:(id)arg1 didChangeToCurrentTime:(float)arg2;
-(void)playerController:(id)arg1 willChangeToDuration:(double)arg2;
-(void)playerController:(id)arg1 didChangeToDuration:(double)arg2;
-(void)playerController:(id)arg1 willChangeToPlaybackState:(long long)arg2;
-(void)playerController:(id)arg1 didChangeToPlaybackState:(long long)arg2;
-(void)playerController:(id)arg1 willChangeToRate:(float)arg2;
-(void)playerController:(id)arg1 didChangeToRate:(float)arg2;
-(void)playerController:(id)arg1 willChangeToStatus:(long long)arg2;
-(void)playerController:(id)arg1 didChangeToStatus:(long long)arg2;
-(void)playerController:(id)arg1 willSeekToTime:(float)arg2;
-(void)playerController:(id)arg1 didSeekToTime:(float)arg2;

@end

