/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UserNotificationsUIKit/UserNotificationsUIKit-Structs.h>
#import <UserNotificationsUIKit/NCAttachmentViewController.h>

@class NCAudioPlayerControlsViewController;

@interface NCAudioAttachmentViewController : NCAttachmentViewController {

	NCAudioPlayerControlsViewController* _playerViewController;

}

@property (nonatomic,retain) NCAudioPlayerControlsViewController * playerViewController;              //@synthesize playerViewController=_playerViewController - In the implementation block
-(CGSize)contentSize;
-(void)dealloc;
-(void)viewDidLoad;
-(NCAudioPlayerControlsViewController *)playerViewController;
-(void)setPlayerViewController:(NCAudioPlayerControlsViewController *)arg1 ;
-(unsigned long long)customContentLocation;
-(id)initWithAttachment:(id)arg1 forNotificationRequest:(id)arg2 ;
@end

