/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:10 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol NCContentSizeCategoryAdjusting <UIContentSizeCategoryAdjusting>
@property (nonatomic,copy) NSString * preferredContentSizeCategory; 
@optional
-(NSString *)preferredContentSizeCategory;
-(void)setPreferredContentSizeCategory:(id)arg1;

@required
-(BOOL)adjustForContentSizeCategoryChange;

@end

