/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UserNotificationsUIKit/UserNotificationsUIKit-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface NCLegacyAdditionalContentAccessoryView : UIView {

	UIView* _contentView;

}

@property (assign,nonatomic,__weak) UIView * contentView;              //@synthesize contentView=_contentView - In the implementation block
-(void)setContentView:(UIView *)arg1 ;
-(UIView *)contentView;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

