/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NCLookViewFontProvider : NSObject {

	BOOL _isDefault;

}
+(id)lookViewPreferredFontProvider;
+(id)lookViewDefaultFontProvider;
-(id)nc_preferredFontForTextStyle:(id)arg1 hiFontStyle:(long long)arg2 ;
-(id)initForProvidingDefaultFonts:(BOOL)arg1 ;
@end

