/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NCLongLookAnimatorDelegate <NCViewControllerAnimatedTransitioningDelegate>
@required
-(void)longLookAnimatorAnimationBegan:(id)arg1;
-(void)longLookAnimator:(id)arg1 animationEnded:(BOOL)arg2;

@end

