/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:12 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NCLongLookPresentationControllerDelegate <NSObject>
@optional
-(BOOL)longLookPresentationControllerShouldIncludePreview:(id)arg1;
-(unsigned long long)longLookPresentationControllerDismissalEdge:(id)arg1;

@required
-(CGRect*)longLookPresentationController:(id)arg1 frameForTransitionViewInPresentationSuperview:(id)arg2;
-(BOOL)longLookPresentationControllerPreviewShouldIncludeShadow:(id)arg1;
-(BOOL)longLookPresentationControllerShouldRestoreSourceView:(id)arg1;

@end

