/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/_UIBackdropViewSettings.h>

@interface NCLookViewBackdropViewSettings : _UIBackdropViewSettings

@property (getter=_isBlurred,nonatomic,readonly) BOOL blurred; 
@property (getter=_isDarkened,nonatomic,readonly) BOOL darkened; 
+(id)lookViewBackdropViewSettingsWithBlur:(BOOL)arg1 darken:(BOOL)arg2 ;
+(id)lookViewBackdropViewSettingsWithBlur:(BOOL)arg1 ;
-(void)setDefaultValues;
-(BOOL)_isDarkened;
-(BOOL)_isBlurred;
@end

