/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:12 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UserNotificationsUIKit/UserNotificationsUIKit-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface NCNotificationClearAllView : UIView {

	UILabel* _clearAllLabel;
	/*^block*/id _clearAllHandler;

}
-(void)layoutSubviews;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)didMoveToSuperview;
-(CGSize)intrinsicContentSize;
-(id)initWithClearAllHandler:(/*^block*/id)arg1 ;
@end

