/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:12 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NCTransitionManagerDelegate <NSObject>
@optional
-(void)transitionManager:(id)arg1 shouldFinishInteractionWithCompletionBlock:(/*^block*/id)arg2;
-(void)longLookWillPresentForTransitionManager:(id)arg1 withSource:(id)arg2;
-(void)longLookWillDismissForTransitionManager:(id)arg1;
-(void)transitionManager:(id)arg1 didPresentLongLook:(BOOL)arg2;
-(void)transitionManager:(id)arg1 didDismissLongLook:(BOOL)arg2;

@required
-(id)longLookViewControllerForTransitionManager:(id)arg1;
-(id)presentingViewControllerForTransitionManager:(id)arg1;
-(BOOL)transitionManager:(id)arg1 shouldBeginInteractionWithSource:(id)arg2;
-(void)transitionManagerWillBeginUserInteraction:(id)arg1;
-(void)transitionManagerDidEndUserInteraction:(id)arg1;

@end

