/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:10 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UserNotificationsUIKit/NCPlusDStyling.h>

@interface NCVibrantWidgetQuaternaryStyling : NCPlusDStyling
-(long long)style;
-(id)color;
-(double)alpha;
@end

