/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 10:30:11 PM Eastern Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIViewControllerAnimatedTransitioning <NSObject>
@optional
-(id)interruptibleAnimatorForTransition:(id)arg1;
-(void)animationEnded:(BOOL)arg1;

@required
-(double)transitionDuration:(id)arg1;
-(void)animateTransition:(id)arg1;

@end

